# SEE: https://github.com/gitleaks/gitleaks/#configuration

[extend]
useDefault = true # SEE: https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml

[[rules]]
description = "IPv4"
id = "ipv4"
regex = '''[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'''

# commented out pending further investigation
# [[rules]]
# id = "password"
# description = "Passwords "
# regex = '''(?i)(?:secret|key|signature|password|pwd|pass|token)(?:\w|\s*?)(?:=){1}(?:\s{0,10})[\"'`](.*?)[\"'`]'''
# [[rules.Entropies]]
#   Min = "3"
#   Max = "7"
#   Group = "1"

# [[rules]]
# id = "AWS account"
# description = "AWS account number  - 12 digits"
# regex = '''[0-9]{12}'''


[[rules]]
description = "DynamoDB Endpoint"
id = "dynamodb"
regex = '''dynamodb\.[a-z]{2}[a-z-]*[1,2,3]\.amazonaws\.com'''

[[rules]]
description = "ARN Generic"
id = "arn"
regex = '''arn:aws:(.*):(.*):[0-9]{12}'''

[[rules]]
description = "ARN S3 "
id = "arns3"
regex = '''arn:aws:s3:::(.*)'''

[[rules]]
description = "ECR Endpoint"
id = "ecr"
regex = '''[0-9]{12}\.dkr\.ecr\.[a-z-]*-[1,2,3]\.amazonaws\.com'''


[[rules]]
description = "Elastic Search Endpoint"
id = "esendpoint"
regex = '''(.*)[a-z-]*[1,2,3]\.es\.amazonaws\.com'''


[[rules]]
description = "Standard Certificate"
id = "standardcertificate"
regex = '''-----BEGIN(\s)CERTIFICATE-----\n'''

[[rules]]
description = "Private Keys"
id = "privatekeys"
regex = '''\s*(\bBEGIN\b).*(PRIVATE KEY\b)\s*'''
