#!/bin/bash -e

# commit-msg git hook runner

# ==============================================================================
project_dir=$(git rev-parse --show-toplevel)
cd $project_dir

printf "Running all commit message hooks\n"
commit_msg_scripts=$(ls -1 $project_dir/scripts/githooks/*-commit-msg.sh 2> /dev/null)
for script in $commit_msg_scripts; do
  printf "Running githook: $(echo $script | sed "s;$project_dir/;;g")\n"
  $script "$@"
done
printf "Successfully run all commit message hooks\n"
