name: Action Account Infrastructure Stacks

on:
  workflow_call:
    inputs:
      github_environment:
        description: "Defines the Github environment in which to pull environment variables from"
        required: true
        type: string
      tf_action:
        description: "Defines the terraform action to run - eg plan,apply etc "
        required: true
        type: string
      tf_vers:
        description: "Version of terraform used"
        required: true
        type: string

jobs:
  build-dev-policies:
    if: contains(inputs.github_environment,'dev')
    runs-on: ubuntu-latest
    environment: ${{ inputs.github_environment }}
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        stack:
          - uec-developer-role
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.tf_vers }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2.2.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/uec-account-mngt-github-runner
          role-session-name: github-pipeline-session
          aws-region: eu-west-2

      - name: Initialise and Run Terraform Apply
        run: |
          export ACTION=${{ inputs.tf_action }}
          export STACK=${{ matrix.stack }}
          export ACCOUNT_PROJECT=${{ vars.ACCOUNT_PROJECT }}
          export ACCOUNT_TYPE=${{ vars.ACCOUNT_TYPE }}
          /bin/bash ./scripts/action-infra-stack.sh

  build-non-dev-policies:
    runs-on: ubuntu-latest
    environment: ${{ inputs.github_environment }}
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        stack:
          - uec-support-role
          - support-tools
          - uec-poweruser-role
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.tf_vers }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2.2.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/uec-account-mngt-github-runner
          role-session-name: github-pipeline-session
          aws-region: eu-west-2

      - name: Initialise and Run Terraform Apply
        run: |
          export ACTION=${{ inputs.tf_action }}
          export STACK=${{ matrix.stack }}
          export ACCOUNT_PROJECT=${{ vars.ACCOUNT_PROJECT }}
          export ACCOUNT_TYPE=${{ vars.ACCOUNT_TYPE }}
          export TF_VAR_aws_serverless_applications_repo_url=${{ vars.AWS_SERVERLESS_APPLICATIONS_REPO_URL }}
          /bin/bash ./scripts/action-infra-stack.sh



