name: Apply terraform

on:
  workflow_call:
    inputs:
      ENV:
        required: true
        type: string

jobs:
  build-dev-policies:
    if: contains(inputs.ENV,'dev')
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENV }}
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        stack:
          - uec-developer-role
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ vars.TF_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2.2.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/uec-account-mngt-github-runner
          role-session-name: github-pipeline-session
          aws-region: eu-west-2

      - name: Initialise and Run Terraform Apply
        run: |
          export ACTION=plan
          export STACK=${{ matrix.stack }}
          export ACCOUNT_PROJECT=${{ vars.ACCOUNT_PROJECT }}
          export ACCOUNT_TYPE=${{ vars.ACCOUNT_TYPE }}
          /bin/bash ./scripts/infra-deploy.sh

  build-non-dev-policies:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENV }}
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        stack:
          - uec-support-role
          - support-tools
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ vars.TF_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2.2.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/uec-account-mngt-github-runner
          role-session-name: github-pipeline-session
          aws-region: eu-west-2

      - name: Initialise and Run Terraform Apply
        run: |
          export ACTION=plan
          export STACK=${{ matrix.stack }}
          export ACCOUNT_PROJECT=${{ vars.ACCOUNT_PROJECT }}
          export ACCOUNT_TYPE=${{ vars.ACCOUNT_TYPE }}
          export TF_VAR_aws_serverless_applications_repo_url=${{ vars.AWS_SERVERLESS_APPLICATIONS_REPO_URL }}
          /bin/bash ./scripts/infra-deploy.sh



