name: Orchestrate terraform workflow

on:
  # workflow_call:
  #   inputs:
  #     account: # the parameter passed in lieu of matrix below
  #       required: true
  #       type: string

  push:
    branches:
      - 'task/DR-316_Proto_type_twr'

jobs:
    validate-terraform-dos-dev:
      name: Validate terraform code dos dev
      uses: ./.github/workflows/validate-terraform.yaml
      with:
        ACCOUNT_TYPE: dev
        ACCOUNT_PROJECT: dos
        ACCOUNT: prod
      secrets: inherit


    # deploy-to-dev:
    #   name: Deploy to dev
    #   uses: ./.github/workflows/terraform-action.yaml
    #   with:
    #     environment-name: dev

