name: Orchestrate terraform workflow

on:
  # workflow_call:
  #   inputs:
  #     account: # the parameter passed in lieu of matrix below
  #       required: true
  #       type: string

  push:
    branches:
      - 'task/DR-316_Proto_type_twr'

jobs:
  # only nee to validate tf code once only once
    validate-terraform-dos-dev:
      name: Validate terraform code dos dev
      uses: ./.github/workflows/validate-terraform.yaml
      with:
        ACCOUNT_TYPE: dev
        ACCOUNT_PROJECT: dos
        ACCOUNT: dos-dev
      secrets: inherit
    apply-terraform-dos-dev:
      name: Validate terraform code dos dev
      uses: ./.github/workflows/apply-terraform-dev.yaml
      with:
        ACCOUNT_TYPE: dev
        ACCOUNT_PROJECT: dos
      secrets: inherit
    apply-terraform-dos-test:
      name: Validate terraform code dos dev
      uses: ./.github/workflows/apply-terraform.yaml
      with:
        ACCOUNT_TYPE: test
        ACCOUNT_PROJECT: dos
        ACCOUNT: dos-test
      secrets: inherit
