name: Orchestrate terraform workflow

on:
  push:
    branches:
      - 'task/DR-406_Add_support_tools'

jobs:
    apply-terraform-dos-dev:
      name: Build account level resources for dos dev account
      uses: ./.github/workflows/apply-terraform.yaml
      with:
        ENV: dos-dev
      secrets: inherit
    apply-terraform-dos-test:
      name: Build account level resources for dos test account
      uses: ./.github/workflows/apply-terraform.yaml
      with:
        ENV: dos-test
      secrets: inherit
    # TODO add other dos related accounts as required
    apply-terraform-cm-dev:
      name: Build account level resources for cm dev account
      uses: ./.github/workflows/apply-terraform.yaml
      with:
        ENV: cm-dev
      secrets: inherit
    apply-terraform-cm-test:
      name: Build account level resources for cm test account
      uses: ./.github/workflows/apply-terraform.yaml
      with:
        ENV: cm-test
      secrets: inherit
    # TODO add other cm related accounts as required
