name: Orchestrate terraform workflow

on:
  push:
    branches:
      - 'task/DR-316_Proto_type_twr'

jobs:
  # only need to validate tf code once only once
    validate-terraform-dos-dev:
      name: Validate terraform code dos dev
      uses: ./.github/workflows/validate-terraform.yaml
      with:
        ACCOUNT_TYPE: dev
        ACCOUNT_PROJECT: dos
        ENV: dos-dev
      secrets: inherit
    apply-terraform-dos-dev:
      name: Build read-write iam policies for dos dev account
      uses: ./.github/workflows/apply-terraform-dev.yaml
      with:
        ACCOUNT_TYPE: dev
        ACCOUNT_PROJECT: dos
        ENV: dos-dev
      secrets: inherit
    apply-terraform-dos-test:
      name: Build read-write and read-only iam policies for dos test account
      uses: ./.github/workflows/apply-terraform.yaml
      with:
        ACCOUNT_TYPE: test
        ACCOUNT_PROJECT: dos
        ENV: dos-test
      secrets: inherit
    # TODO add other dos related accounts as required
    apply-terraform-cm-dev:
      name: Build read-write iam policies for cm dev account
      uses: ./.github/workflows/apply-terraform-dev.yaml
      with:
        ACCOUNT_TYPE: dev
        ACCOUNT_PROJECT: cm
        ENV: cm-dev
      secrets: inherit
    apply-terraform-cm-test:
      name: Build read-write and read-only iam policies for cm test account
      uses: ./.github/workflows/apply-terraform.yaml
      with:
        ACCOUNT_TYPE: test
        ACCOUNT_PROJECT: dos
        ENV: cm-test
      secrets: inherit
    # TODO add other cm related accounts as required
