name:  Master plan

on:
  push:
    branches:
      - 'task/DR-316_Proto_type_twr'
  # workflow_dispatch:
  #   inputs:
  #     environment:
  #       type: choice
  #       description: Choose the Environment
  #       required: true
  #       options:
  #         - dev
  #         - preprod
  #         - prod
  #         - security
  #         - test

jobs:
  account-matrix:
    name: Trigger per account
    strategy:
      fail-fast: false
      matrix:
        acc: ["dev"]
    uses: ./.github/workflows/plan-terraform.yaml
    with:
      account: ${{matrix.acc}}
    # secrets: inherit
