name: Validate terraform

on:
  workflow_call:
    inputs:
      ENV:
        required: true
        type: string

jobs:

  validate-against-tf-versions:
    name: Validate terraform against the min/max versions
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENV }}
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        stack:
          - uec-developer-role
          - uec-support-role
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2.2.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/uec-account-mngt-github-runner
          role-session-name: github-pipeline-session
          aws-region: eu-west-2

      - name: Install Terraform v${{ vars.TF_VERSION }}
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ vars.TF_VERSION }}

      - name: Initialize terraform and validate stack ${{ matrix.stack }} against v${{ vars.TF_VERSION }}
        run: |
          export ACTION=validate
          export STACK=${{ matrix.stack }}
          export ACCOUNT_PROJECT=${{ vars.ACCOUNT_PROJECT }}
          export ACCOUNT_TYPE=${{ vars.ACCOUNT_TYPE }}
          /bin/bash ./scripts/infra-deploy.sh
